{% set version = "3.10.30" %}
{% set name = "XCircuit" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/RTimothyEdwards/{{ name }}/archive/refs/tags/{{ version }}.tar.gz

requirements:
  build:
    - make
    - tk
    - cairo
    # - ltc
    # - libx11
    # - build-essential
    # - build-essential
    # - flex
    # - readline
    # - bison
    # - autoconf
    # - automake
    # - libtool

