{% set version = "1.0.461" %}
{% set name = "open_pdks" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url:  https://github.com/RTimothyEdwards/{{ name }}/archive/refs/tags/{{ version }}.tar.gz

requirements:
  build:
    - make

