{% set version = "1.4.101" %}
{% set name = "qflow" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/johnnycubides/{{ name }}/archive/refs/tags/{{ version }}.tar.gz

dependencies:
  - conda-forge::ncurses
  - conda-forge::tcsh
  - conda-forge::libstdcxx-ng
  - johnnycubides::netgen
  - johnnycubides::magic
  - johnnycubides::qrouter
  - johnnycubides::yosys
  - johnnycubides::graywolf
  - johnnycubides::irsim

requirements:
  build:
    - make
    - autoconf
    # - automake
    # - libtool
    # - tk
    # - cairo
    # - tcl # No existe
    # - libx11 # No existe
    # - build-essential # No existe
    # - flex
    # - readline
    # - bison

## Manual install
# conda install -c conda-forge libstdcxx-ng
# conda install -c conda-forge ncurses
# conda install -c johnnycubides netgen
# conda install -c johnnycubides magic
# conda install -c johnnycubides qrouter
# conda install -c johnnycubides yosys
# conda install -c johnnycubides graywolf
# conda install -c johnnycubides irsim
