{% set version = "1.5.264" %}
{% set name = "netgen" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/RTimothyEdwards/netgen/archive/refs/tags/{{ version }}.zip

requirements:
  build:
    - make
