{% set version = "40" %}
{% set name = "ngspice" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://sourceforge.net/projects/ngspice/files/ng-spice-rework/{{ version }}/{{ name }}-{{ version }}.tar.gz

requirements:
  build:
    - flex
    - readline
    - make
    - bison
    - autoconf
    - automake
    - libtool

